### ISSUE TITLE
NewRelic.Agent.Api package dependency requires an assembly binding redirect

### ISSUE THREAD

**Issue by alex-namely** [newrelic/newrelic-logenricher-dotnet#113]
Hello everybody,

It seems like **NewRelic.LogEnrichers** still uses old versions of it's dependencies.

For example **NewRelic.Agent.Api** package has already bumped the major version and it is required to use an assembly binding mechanism at own risk to fix incompatibility issues.

```xml
<dependentAssembly>
	<assemblyIdentity name="NewRelic.Api.Agent" publicKeyToken="06552fced0b33d87" culture="neutral" />
	<bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
</dependentAssembly>
```

Would you be so kind as to upgrade the package references to the latest versions?

Some links
- https://github.com/newrelic/newrelic-logenricher-dotnet/blob/main/src/NewRelic.LogEnrichers.Log4Net/NewRelic.LogEnrichers.Log4Net.csproj#L18
- https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/

**Comment by alex-namely** [comment]
Hi @jaffinito 
Are you maintaining this repository? 
Can you please have a look to this issue since it's even more important now when NewRelic.Api.Agent is on 10.0.0 version

**Comment by angelatan2** [comment]
@alex-namely, Thank you for submitting this issue and bringing the dependency problem to our attention.  We will take a look at it in the upcoming bug smash.

**Comment by JcolemanNR** [comment]
Hello @alex-namely, can you provide some more information about your use case? We have tested on our team and do not see a need for binding redirects. 

Is this a .NET Framework or .NET Core/Platform application? What version?
What type of application is this? 
Are you using nuget to get the log enricher?
When/where are you seeing an error about a binding redirect being needed? Build? Run?
Can you share what your nuget/assembly references look like?

**Comment by alex-namely** [comment]
Hello @JcolemanNR 

Thank you for reaching out to me.

**Runtime**
.NET Framework 4.8 

**NuGet packages**
`<PackageReference Include="NewRelic.LogEnrichers.Log4Net" Version="1.1.1" />`
`<PackageReference Include="log4net" Version="2.0.12" />`

**Log4Net configuration**
```
<appender name="NewRelicLogsAppender" type="NewRelic.LogEnrichers.Log4Net.NewRelicAppender, NewRelic.LogEnrichers.Log4Net" >
	<threshold value="ERROR"/>
</appender>
```

**Comment by JcolemanNR** [comment]
Hello @alex-namely,

Thanks for the response! So I looked at my test app and realized that it DOES require a binding redirect, but my experience is that the package manager in visual studio automatically adds those. Is this not the behavior you are seeing?

As the agent API does not frequently change, and only new functionality is typically added, the risk of this breaking anything is very low.

Can you clarify your concerns with the binding redirect, and explain how the need for a binding redirect creates a pain point for you?

**Comment by angelatan2** [comment]
@sdelavega This issue is reported by our community on the agent and not internal systems.

**Comment by alex-namely** [comment]
@JcolemanNR , @vuqtran88 
You are probably right, if packages are compatible between 8 and 10 version so risk of breaking anything is very low.

Also with introducing automatic logs forwarding feature there is no longer a big need to use this packages. 
Once automatic logs forwarding introduce a possibility to choose logging level (e.g. send only errors to NewRelic to reduce cost) we will delete this package. 

Feel free to close this issue and thank you for response.
