### ISSUE TITLE
Add option to remove "Message.Properties" prefix from custom enriched properties

### ISSUE THREAD

**Issue by NiklasArbin** [newrelic/newrelic-logenricher-dotnet#121]
## Description
All custom enriched properties are renamed with prefix Message.Properties.

## Expected Behavior
Custom enriched properties should respect name, or at least open for the possibility of overriding the default behavior.

## Steps to Reproduce
Enrich your logger with for instance userid. User id is now logged as Message.Properties.userid

**Comment by jaffinito** [comment]
Hi @NiklasArbin thank you for reaching out about this.  The idea behind adding the "Message.Properties" prefix was to make it easier to find them in our UI.  Adding a configuration flag for allow for that to be disable could be possible, we will need to double check and see what our backend is expecting.

**Comment by jaffinito** [comment]
After doing some digging into our old MMF docs and the like, I am not finding anything that says we have to add "Message.Properties" as a prefix to attributes.  I think a quick spike would be helpful to just confirm that the UI is happy with not having the prefix (I don't see why not),

**Comment by NiklasArbin** [comment]
Would you accept a pull request for this?

**Comment by chynesNR** [comment]
@NiklasArbin Absolutely!

**Comment by chynesNR** [comment]
Thanks again to @NiklasArbin for the contribution!
