### ISSUE TITLE
Upgrade to NLog 4.5.11

### ISSUE THREAD

**Issue by snakefoot** [newrelic/newrelic-logenricher-dotnet#43]
Many improvements has been made in JsonLayout from NLog 4.5 to [NLog  4.5.11](https://www.nuget.org/packages/NLog/4.5.11)

https://github.com/newrelic/newrelic-logenricher-dotnet/blob/f6b74acbb932fd8d29d52523b79555a11e672d32/src/NLog/NewRelic.LogEnrichers.NLog/NewRelic.LogEnrichers.NLog.csproj#L44

Also recommend assigning `MaxRecursionLimit = 1 ` as it will give better user experience (Was kept to 0 in NLog 4.5 to avoid breaking change for those upgrading from NLog 4.4)

**Comment by nrcventura** [comment]
Since this code ultimately results in a NuGet package and a consumer of this library will already have a dependency on a specific version of NLog, is it still recommended to set our minimum required version of NLog to 4.5.11? Version 4.5.0 was primarily chosen because that was when .NET Standard support was added to NLog.

**Comment by snakefoot** [comment]
> is it still recommended to set our minimum required version of NLog to 4.5.11?

Yes because this is an advanced wrapper around NLog JsonLayout. And it will give the best user-experience if your users doesn't have to re-discover the bugs in the JsonConverter that have been fixed between NLog 4.5 and NLog to 4.5.11.

When users take dependency on your nuget-package, then they probably value correct Json-output.

NLog 4.5 was the first attempt to perform Json-output with support for reflection of rogue objects. This revealed a lot of nitty-gritty details, that have been fixed in newer NLog versions.

**Comment by nr-ahemsath** [comment]
Thanks for submitting your feedback to our project!  We believe we have addressed your recommendations in this PR: https://github.com/newrelic/newrelic-logenricher-dotnet/pull/44

Closing this issue as resolved.

**Comment by snakefoot** [comment]
Looks great. Thanks for the fast response, and enjoy the weekend.
