### ISSUE TITLE
Seems to cause runtime errors

### ISSUE THREAD

**Issue by srulandhs** [newrelic/newrelic-logenricher-dotnet#54]
After a package update, I am seeing the following **runtime** error. Compile is fine.

`
Inner Exception 1:
FileLoadException: Could not load file or assembly 'NewRelic.Api.Agent, Version=8.20.262.0, Culture=neutral, PublicKeyToken=06552fced0b33d87'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
`

NewRelic.Agent.Api (8.28.0)
NewRelic.LogEnrighers.Serilog (1.0.1)

Reverting back to the following, it everything works
NewRelic.Agent.Api (8.27.139)

**Comment by nr-ahemsath** [comment]
Thank you for bringing this to our attention!  If the workaround of reverting to agent version 8.27 is causing issues for you, please let us know.

**Comment by nr-ahemsath** [comment]
There was a bug in the 8.28.0 version of the `NewRelic.Agent.Api` and it has been removed from NuGet.  The most recent versions do not have this bug.  Closing this issue.
