### ISSUE TITLE
Enricher doesn't change output

### ISSUE THREAD

**Issue by natureventyrnu** [newrelic/newrelic-logenricher-dotnet#57]
Hi, I've just installed Serilog, and I'm getting log messages like this:

```{"timestamp":1597221824485,"log.level":"Information","message.template":"User logged in.","message":"User logged in.","Message.Properties.SourceContext":"Proj.Web.Areas.Admin.Pages.LoginModel","Message.Properties.ActionId":"cc2880e6-fa97-4fcc-a28c-f58895fa0d05","Message.Properties.ActionName":"/Login","Message.Properties.RequestId":"0HM1UJF7U0DNB:00000001","Message.Properties.RequestPath":"/Admin/Login","Message.Properties.CorrelationId":null,"Message.Properties.ConnectionId":"0HM1UJF7U0DNB"}```

When adding the newrelic enricher, I do not get any new fields added to the output?

The code I'm using to configure serilog is:

```
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning) // <- Request logging
                .Enrich.WithNewRelicLogsInContext()
                .WriteTo.Console(new NewRelicFormatter())
                .CreateLogger();
```

Which fields should the enricher add, and how come the output doesn't change when adding                `.Enrich.WithNewRelicLogsInContext()`?

**Comment by nr-ahemsath** [comment]
Hello, thanks for bringing this issue to our attention.

Do you also have the [New Relic .NET Agent](https://github.com/newrelic/newrelic-dotnet-agent) enabled for your application?  Unless the agent is attached to the process using the enricher, no additional fields will be added to log events.

Thanks,
Alex

**Comment by natureventyrnu** [comment]
Hey, thank you for your answer.

I wasn't running the agent locally, so that would explain that there were no changes. But on production, I'm running my .net core app in a docker container, and in the container, I have installed: newrelic-netcore20-agent_8.30.0.0_amd64.deb

I get data reported to new relic, but I have not done anything to attach it to the .net processes (except installed it in the docker container). All reporting is done through stdout -> aws cloudwatch which is then reported to new relic through the lambda method (newrelic-log-ingestion). The code has configured it to write to Console.

I've also installed NewRelic.Agent.Api through NuGet (note that I have just installed the nuget package, but haven't used it in any code)

An example of a logged entry from production (with the agent running):
```
{
    "timestamp": 1597259225808,
    "log.level": "Information",
    "message.template": "User logged in.",
    "message": "User logged in.",
    "Message.Properties.SourceContext": "MyProject.Web.Areas.Admin.Pages.LoginModel",
    "Message.Properties.ActionId": "d323674e-3c0c-462e-a30f-ae0840868f43",
    "Message.Properties.ActionName": "/Login",
    "Message.Properties.RequestId": "0HM1UU88S9MRU:00000006",
    "Message.Properties.RequestPath": "/Admin/Login",
    "Message.Properties.CorrelationId": null,
    "Message.Properties.ConnectionId": "0HM1UU88S9MRU",
    "entity.name": "MyProject_production",
    "entity.type": "SERVICE",
    "entity.guid": "xxxxxxxxxxx",
    "hostname": "xxxxxxxxxx.eu-central-1.compute.internal"
}
```
Has that been enriched by the newrelic enricher? (I'm uncertain about which fields are added)

**Comment by nr-ahemsath** [comment]
`entity.type` and `entity.guid` are definitely coming from the enricher, so it looks like you've been successful in setting up the use of the enricher with the agent.

**Comment by natureventyrnu** [comment]
Thanks, wasn't sure exactly how much it was adding. Thank you for your help :)
