### ISSUE TITLE
Update Agent API Version to 8.32+ in support of Nullable Reference Types

### ISSUE THREAD

**Issue by jifeingo** [newrelic/newrelic-logenricher-dotnet#77]
## Feature Description
The .NET Agent v8.32 in support Nullable Reference Types feature of C# 8.0.
This Issue is to update the API NuGet package reference to the current version (which has nullable ref types)

**Comment by angelatan2** [comment]
@jifeingo can you share what are the forcing functions for this support to inform a need by date?
