### ISSUE TITLE
Include inner exceptions in serilog formatter

### ISSUE THREAD

**Issue by dswisher** [newrelic/newrelic-logenricher-dotnet#83]
## Is your feature request related to a problem? Please describe.
When debugging an issue, it is supremely helpful to see the inner exception associated with an exception. Currently, the serilog formatter does not include this information.

## Feature Description
Include the inner exception details when logging an exception. One possibility would be to change `exception.StackTrace` to `exception.ToString()` [here](https://github.com/newrelic/newrelic-logenricher-dotnet/blob/main/src/NewRelic.LogEnrichers.Serilog/NewRelicFormatter.cs#L109). Granted, that means it is no longer technically a stack trace, but it does provide more useful information.

## Describe Alternatives
One alternative would be to include a new property, something like `error.full` or similar?

## Priority
Must Have

-- Internal note --
Integrated to JIRA

**Comment by nrcventura** [comment]
@elucus This is something that should be evaluated from the Product Manager side of things. From the engineering perspective there are many things that could be done. Here are some ideas:

1. Do what's suggested in this ticket. - The downside to this is that we end up with something that doesn't look like a stack trace in the strack trace property. This may or may not be a problem with the UI, but should be something that is discussed with that group.
2. Add an additional property that would be .NET only that can include the entirety of exception.ToString(). - The downside to this is that this additional field may be subject to a size limit, and may end up truncated. This should be discussed with the logging group.
3. Customer specific workarounds. - This solution would probably vary on a case by case basis. For example, a customer could choose to just log the inner exception, or they could enrich the log messages with details from the inner exception (the New Relic tries to include all of the information that other enrichers have added).

**Comment by elucus** [comment]
I've discussed it with the Logging team.

1. error.stack is an attribute with no special processing or UI logic. However, a customer can still have an existing query looking for a specific string/format in the error.stack field, so we don't want to make changes to it.
2. This is our best option. The data will be limited to 4096 characters, but that is the same as any other attribute, including the message field.
3. Can be used if an immediate fix is needed.

@dswisher this isn't on our immediate roadmap, but if you're interested in helping out, we'd be happy to review the PR and push a new version.

**Comment by chase-miller** [comment]
Why not use an enricher specifically for this purpose? Something like https://github.com/RehanSaeed/Serilog.Exceptions

**Comment by nr-ahemsath** [comment]
@chase-miller: thanks for your contribution.  Can you clarify whether your suggestion is directed at @dswisher or at our team at New Relic?
