### ISSUE TITLE
Log4net - Log level is not recognized

### ISSUE THREAD

**Issue by ltines** [newrelic/newrelic-logenricher-dotnet#84]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
log4net log level is serialized as `"log.level":{"Name":"INFO","Value":40000,"DisplayName":"INFO"}` which NR doesn't recognize as a valid log level.
![image](https://user-images.githubusercontent.com/5260112/97288285-8e09a300-183d-11eb-859d-4c89206a8853.png)

It should output just `"log.level":"INFO"`
## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
When set up log4net NewRelic Layout according to https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-net/net-configure-log4net the `NewRelicLayout` outputs `dictionary.Add(LoggingExtensions.GetOutputName(NewRelicLoggingProperty.LogLevel), loggingEvent.Level);`. The problem here is `loggingEvent.Level` is a class which gets serialized.

It should just use `loggingEvent.Level.Name`
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
Pass log level NR can parse and recognize

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
Windows Server 2019, latest NR .NET Agent and NR Infrastructure Agent

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by nr-ahemsath** [comment]
Hi @ltines, thanks for bringing this to our attention and submitting a PR to solve the issue.  I'll need to do some testing on our end but I hope we can get this merged quickly, hopefully by the end of the week at the latest.

**Comment by ltines** [comment]
@nr-ahemsath appreciate it
