### ISSUE TITLE
Upgrade example apps to a supported .NET version

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-logenricher-dotnet#90]
We need to upgrade our example apps to .NET Core 3.1.  However, when we tried doing this to one app (Log4Net) recently, our security scan tool (Synk) had an error.  Once we have determined how to resolve this issue, we can do this upgrade.

**Comment by tippmar-nr** [comment]
Updated to netframework462 and net7.0 via PR #142
