### ISSUE TITLE
Dockerized examples that include log forwarding setup to demonstrate/test end-to-end functionality

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-logenricher-dotnet#91]
It will be helpful for all concerned if we have some dockerized demos using our sample apps that include the log forwarding configuration, to easily demo and/or test end-to-end functionality.

**Comment by angelatan2** [comment]
@nr-ahemsath Given that this enhancement has not risen in priority for the last two years,  I'm closing it out as won't do.
